package com.example.pamprojcw

enum class ProductType {
    FOOD_AND_BEVERAGE,
    CLOTHING_AND_ACCESSORIES,
    HEALTH_AND_PERSONAL_CARE,
    HOME_AND_GARDEN,
    ELECTRONICS,
    SPORTS_AND_OUTDOOR_GEAR,
    BEAUTY_AND_GROOMING,
    TRAVEL,
    ENTERTAINMENT,
    EDUCATION_AND_TRAINING,
    TRANSPORTATION,
    CHARITABLE_DONATIONS,
    SUBSCRIPTIONS,
    OFFICE_SUPPLIES,
    SCHOOL_SUPPLIES,
    FINANCIAL_SERVICES
}